---
title: "kbolton_hw2"
author: "Katie Bolton"
output: html_document
---

```{r setup, include=FALSE}
require(rgdal)
require(leaflet)
require(leaflet.extras)
require(dplyr)
require(stringr)
require(tigris)
```

## A few interesting basemaps


```{r, controls}
leaflet() %>%
  # Basemaps
  addTiles(group = "default") %>%
  addProviderTiles(providers$Esri.NatGeoWorldMap, group = "NatGeo") %>%
  addProviderTiles(providers$OpenStreetMap.BlackAndWhite, group = "BlackWhite") %>%
  addProviderTiles(providers$JusticeMap.income, group = "income") %>%
  # Layers control
  addLayersControl(
    baseGroups = c("default", "NatGeo", "BlackWhite", "income"),
    options = layersControlOptions(collapsed = FALSE)
  )
```

## Counties in Florida Shapefile

```{r, counties}
counties <- readOGR("Florida_Counties/Florida_Counties.shp",
  layer = "Florida_Counties", GDAL1_integer64_policy = TRUE)
results2016 <- read.csv("countyvotes.csv")
countiesVote <- geo_join(counties, results2016, by = "COUNTYNAME")
pal <- colorNumeric(
  palette = colorRamp(c("#0000FF", "#FF0000"), interpolate="linear"),
  domain = c(0,1)
  )
leaflet(countiesVote) %>%
  addTiles() %>%
  addPolygons(color = ~pal(Trumpvote), label = ~COUNTYNAME) %>%
  addLegend("bottomleft", pal = pal, values = ~Trumpvote,
            title = "proportion of votes for Trump")
```


## FL bus transit routes 2008 

```{r, transit}
buses <- readOGR("trrts_2008/trrts_2008.shp",
  layer = "trrts_2008", GDAL1_integer64_policy = TRUE)
buses <- spTransform(buses, CRS("+proj=longlat +datum=WGS84 +no_defs"))
leaflet(buses) %>%
  addProviderTiles(providers$OpenStreetMap.BlackAndWhite) %>%
  addPolylines()
```

## FL mobile home parks 2019

```{r, mobile-home-parks}
mobileHomes <- read.csv("Mobile_Home_Parks_in_Florida_2019.csv")
colnames(mobileHomes)[1] <- "X"
buses <- readOGR("trrts_2008/trrts_2008.shp",
  layer = "trrts_2008", GDAL1_integer64_policy = TRUE)
buses <- spTransform(buses, CRS("+proj=longlat +datum=WGS84 +no_defs"))
leaflet(mobileHomes) %>%
  addTiles() %>%
  addCircleMarkers(lng = ~X, lat = ~Y, radius = 1, group = "Mobile Home Parks") %>%
  addPolylines(data = buses, group = "Public Transit Routes") %>%
    # Layers control
  addLayersControl(
    baseGroups = c("Mobile Home Parks", "Public Transit Routes"),
    options = layersControlOptions(collapsed = FALSE)
  )
```